[workspace]
authors = ["faramirZ <faramirzailan@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "neondisco-jet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
star = "*"
samtools = "1.3.*"
nextflow = ">=26.4.6,<27"
ncurses = ">=6.6,<7"
graphviz = ">=14.1.2,<15"
